routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('generate-pdf','TransactionInfoController@generatePDF');

Route::get('/', function () {
    return view('guest/home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// new
// Route::post('/register', 'AuthController@register');
// Route::post('/login', 'AuthController@login');

Route::get('/admin', function () {
    if (Auth::check()) {
        return redirect()->action('HomeController@index');
    }
    return view('auth.admin.login');
});

Route::get('/guest', function () {
    return view('guest/home');
});
Route::get('/user/chooseStore', 'StoreController@chooseStore')->name('chooseStore');

Route::get('/plan_price/json', 'PlanPriceController@listPrice');

// Route::get('/guest/store', function () {
//     return view('guest/store/choose_store');
// });
// Route::get('/guest/store/create', function () {
//     return view('guest/store/create_store');
// });

// user middleware
Route::middleware('auth')->group(function () {
    Route::get('/user', function () {
        
    });
    Route::get('/user/inventory', function () {
        return view('user/inventory');
    });
    Route::get('/user/report', function () {
        return view('user/report');
    });
    Route::resource('stores', 'StoreController');
    Route::get('stores/{id}/activate', 'StoreController@activate');
    Route::resource('categories', 'CategoryController');
    Route::resource('products', 'ProductController');
    Route::get('product/image/{image}', 'ProductController@apiShowImage');
    
    Route::resource('contacts', 'ContactController');
    Route::resource('transactions', 'TransactionController');
    Route::resource('transaction_infos', 'TransactionInfoController');
    // Route::get('search','ProductController@search');
    
    // admin middleware
    Route::middleware('admin')->group(function () {
        Route::get('/admin/home', function () {
            return view('admin.dashboard');
        });
        Route::resource('plan_prices', 'PlanPriceController');
        Route::get('stores/{id}/deactivate', 'StoreController@deactivate');

        Route::resource('users', 'UserController');
        Route::get('users/{id}/activate', 'UserController@activate');
        Route::get('users/{id}/deactivate', 'UserController@deactivate');
    });
});

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $fillable = [
        'name',
        'role',
        'telephone',
        'description',
        'store_id'
    ];
}

app/User.php
<?php

namespace App;

use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 
    ];

    // protected function create(array $data)
    // {
    //     return User::create([
    //         'name' => $data['name'],
    //         'email' => $data['email'],
    //         'password' => Hash::make($data['password']),
    //         'api_token' => Str::random(60),
    //     ]);
    // }

}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Contact;
use App\Http\Resources\ContactResource;
use Illuminate\Http\Request;
use Session;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contacts = Contact::where('contacts.store_id','=',Session::get('store')['store_id'])->paginate(5);

        return view('user/contact/view_contact', compact('contacts'));
    }

    public function apiShowAll(Request $request)
    {
        $request->validate([
            'store_id'=>'required',
        ]);

        $contacts = Contact::where('store_id','=',$request->get('store_id'))->get();

        return response()->json([
            'response' => 1,
            'data' => $contacts,
        ], 200);
    }

    public function apiShow($id)
    {
        $contact = Contact::where('id','=',$id)->get();

        return response()->json([
            'response' => 1,
            'data' => $contact,
        ], 200);
    }

    public function apiAdd(Request $request) {
        $request->validate([
            'name'=>'required',
            'store_id'=>'required',
        ]);
          
        $contact = new contact([
            'name' => $request->get('name'),
            'role' => $request->get('role'),
            'store_id' => $request->get('store_id'),
            'telephone' => $request->get('telephone'),
            'description' => $request->get('description'),
        ]);
          
        $contact->save();

        return response()->json([
            'response' => 1,
            'message' => 'Contact has been added',
            'data' => $contact,
        ], 200);
    }

    public function apiUpdate(Request $request)
    {
        $request->validate([
            'id' => 'required',
            'name' => 'required',
            'store_id' => 'required',
        ]);
        
        $contact = Contact::find($request->get('id'));

        if ($contact) {
            if ($contact->store_id != $request->get('store_id')) {
                return response()->json([
                    'response' => 0,
                    'message' => 'Invalid store id',
                ], 401);
            }

            $contact->name = $request->get('name');
            $contact->role = $request->get('role');
            $contact->telephone = $request->get('telephone');
            $contact->description = $request->get('description');
            $contact->save();

            return response()->json([
                'response' => 1,
                'message' => 'Contact has been updated',
                'data' => $contact,
            ], 200);
        }
        else {
            return response()->json([
                'response' => 0,
                'message' => 'Invalid contact id',
            ], 401);
        }
    }

    public function apiDelete(Request $request)
    {
        $request->validate([
            'id' => 'required',
            'store_id' => 'required',
        ]);
        
        $contact = Contact::find($request->get('id'));
        
        if ($contact) {
            if ($contact->store_id != $request->get('store_id')) {
                return response()->json([
                    'response' => 0,
                    'message' => 'Invalid store id',
                ], 401);
            }

            $contact->delete();
   
            return response()->json([
                'response' => 1,
                'message' => 'Contact has been deleted',
            ], 200);
        }
        else {
            return response()->json([
                'response' => 0,
                'message' => 'Invalid contact id',
            ], 401);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user/contact/add_contact');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
          ]);
          
        $contact = new contact([
            'name' => $request->get('name'),
            'role' => $request->get('role'),
            'store_id' => Session::get('store')['store_id'],
            'telephone' => $request->get('telephone'),
            'description' => $request->get('description'),
            ]);
        $contact->save();
        return redirect('contacts')->with('success', 'Contact has been added');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $contact= Contact::find($id);

        return view('user/contact/edit_contact', compact('contact'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
        ]);
    
        $contact = Contact::find($id);
        $contact->name = $request->get('name');
        $contact->role = $request->get('role');
        $contact->telephone = $request->get('telephone');
        $contact->description = $request->get('description');
        $contact->save();
    
        return redirect('contacts')->with('success', 'Contact has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $contact = Contact::find($id);
        $contact->delete();
   
        return redirect('contacts')->with('success', 'Contact has been deleted Successfully');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Http\Resources\UserResource;
use Illuminate\Http\Request;
use Session;

class UserController extends Controller
{
    public function index()
    {
        $users =  User::all(); 

        return view('admin/users/view_users', compact('users'));
    }

    public function apiShow(User $user) : UserResource 
    {
        return new UserResource($user);
    }

    public function activate($id)
    {
        $users = User::find($id);
        $users->isActive = 1;
        $users->save();

        if(auth()->user()->isAdmin == 1){

            return redirect('users')->with('success', 'User has been activated');
            
        }
        return view('users');
    }

    public function deactivate($id)
    {
        
        $users = User::find($id);
        $users->isActive = 0;
        $users->save();

        return redirect('users')->with('success', 'Store has been deactivated');
    }

    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
   
        return redirect('users')->with('success', 'User has been deleted Successfully');
    }


}

resources/views/user/contact/add_contact.blade.php
@extends('auth.layouts.layout')

@section('content')
<div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-12">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">{{ __('Add Contact!') }}</h1>
                  </div>
                  <form method="POST" action="{{ route('contacts.store') }}" class="user">
                        @csrf

                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" name="name"
                         id="exampleFirstName" placeholder="Contact Name" value="{{ old('name') }}" required autocomplete="name" autofocus>
                    </div>

                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" name="role"
                       id="exampleFirstName" placeholder="Contact Role" value="{{ old('role') }}">
                    </div>

                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" name="telephone"
                       id="exampleFirstName" placeholder="Telephone" value="{{ old('telephone') }}">
                    </div>

                    <div class="form-group">
                      <textarea rows="4" cols="50" name="description" class="form-control" placeholder="Contact Description..."></textarea>
                    </div>

                    <hr>

                    <button type="submit" class="btn btn-primary btn-user btn-block">
                        {{ __('Add') }}
                    </button>

                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
    
      </div>
@endsection

resources/views/user/contact/edit_contact.blade.php
@extends('auth.layouts.layout')

@section('content')
<div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-12">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">{{ __('Update Contact!') }}</h1>
                  </div>
                  <form method="POST" action="{{ route('contacts.update', $contact->id) }}" class="user">
                        @csrf
                        @method('PATCH')
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" name="name"
                         id="exampleFirstName" placeholder="Contact Name" value="{{ $contact->name }}" required autocomplete="name" autofocus>
                    </div>

                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" name="role"
                       id="exampleFirstName" placeholder="Contact Role" value="{{ $contact->role }}">
                    </div>

                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" name="telephone"
                      id="exampleFirstName" placeholder="Telephone" value="{{ $contact->telephone }}">
                    </div>
                    
                    <div class="form-group">
                      <textarea rows="4" cols="50" name="description" class="form-control" placeholder="Contact Description...">{{ $contact->description }}</textarea>
                    </div>
                    
                    <hr>

                    <button type="submit" class="btn btn-primary btn-user btn-block">
                        {{ __('Update') }}
                    </button>

                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
    
      </div>
@endsection

resources/views/user/contact/view_contact.blade.php
@extends('user.layouts.layout')

@section('content')

        <!-- Begin Page Content -->
        <div class="container-fluid">
            @if(session()->get('success'))
              <div class="alert alert-success">
                {{ session()->get('success') }}  
              </div><br />
            @endif
          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800">Contacts</h1>

          <?php
              $contact_size = $contacts->total();
          ?>

          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Contact: {{$contact_size}}</h6>
                  <div class="text-right">
                      <a class="btn btn-primary" href="{{ route('contacts.create') }}">
                        {{ __('Add Contact') }}
                      </a>
                  </div>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  @if($contact_size > 0)
                  <thead align="center">
                    <tr>
                      <th>No.</th>
                      <th>Name</th>
                      <th>Role</th>
                      <th>Telephone</th>
                      <th>Description</th>
                      <th colspan="2">Action</th>
                    </tr>
                  </thead>
                  <tbody align="center">
                    <?php 
                        $count = $contacts->firstItem();
                    ?>
                      @foreach($contacts as $contact)
                        <tr>
                          <td>{{ $count++ }}</td>
                          <td>{{ $contact->name }}</td>
                          <td>{{ $contact->role }}</td>
                          <td>{{ $contact->telephone }}</td>
                          <td>{{ $contact->description }}</td>
                          <td>
                              <a class="btn btn-warning" href="{{ route('contacts.edit', $contact->id) }}">
                                  {{ __('Update') }}
                              </a>
                          </td>
                          <td>
                              <form action="{{ route('contacts.destroy', $contact->id) }}" method="POST">
                                  @method('DELETE')
                                  @csrf
                                  <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')">
                                      {{ __('Delete') }}
                                  </button>
                              </form>
                          </td>
                        </tr>
                      @endforeach
                      @while(($count-1) % 5 != 0)
                      <tr>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                      </tr>
                      <?php $count++ ?>
                      @endwhile
                  </tbody>
                  @else
                      <p>You have 0 contact!</p>
                  @endif
                </table>
                  <div class="text-right">
                      {{ $contacts->onEachSide(5)->links() }}
                  </div>
              </div>
            </div>
          </div>

        </div>
        <!-- /.container-fluid -->
@endsection