routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('generate-pdf','TransactionInfoController@generatePDF');

Route::get('/', function () {
    return view('guest/home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// new
// Route::post('/register', 'AuthController@register');
// Route::post('/login', 'AuthController@login');

Route::get('/admin', function () {
    if (Auth::check()) {
        return redirect()->action('HomeController@index');
    }
    return view('auth.admin.login');
});

Route::get('/guest', function () {
    return view('guest/home');
});
Route::get('/user/chooseStore', 'StoreController@chooseStore')->name('chooseStore');

Route::get('/plan_price/json', 'PlanPriceController@listPrice');

// Route::get('/guest/store', function () {
//     return view('guest/store/choose_store');
// });
// Route::get('/guest/store/create', function () {
//     return view('guest/store/create_store');
// });

// user middleware
Route::middleware('auth')->group(function () {
    Route::get('/user', function () {
        
    });
    Route::get('/user/inventory', function () {
        return view('user/inventory');
    });
    Route::get('/user/report', function () {
        return view('user/report');
    });
    Route::resource('stores', 'StoreController');
    Route::get('stores/{id}/activate', 'StoreController@activate');
    Route::resource('categories', 'CategoryController');
    Route::resource('products', 'ProductController');
    Route::get('product/image/{image}', 'ProductController@apiShowImage');
    
    Route::resource('contacts', 'ContactController');
    Route::resource('transactions', 'TransactionController');
    Route::resource('transaction_infos', 'TransactionInfoController');
    // Route::get('search','ProductController@search');
    
    // admin middleware
    Route::middleware('admin')->group(function () {
        Route::get('/admin/home', function () {
            return view('admin.dashboard');
        });
        Route::resource('plan_prices', 'PlanPriceController');
        Route::get('stores/{id}/deactivate', 'StoreController@deactivate');

        Route::resource('users', 'UserController');
        Route::get('users/{id}/activate', 'UserController@activate');
        Route::get('users/{id}/deactivate', 'UserController@deactivate');
    });
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name',
        'category_id',
        'amount',
        'price_in',
        'price_out',
        'measure_unit',
        'image_path',
        'store_id'
      ];
}

app/User.php
<?php

namespace App;

use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 
    ];

    // protected function create(array $data)
    // {
    //     return User::create([
    //         'name' => $data['name'],
    //         'email' => $data['email'],
    //         'password' => Hash::make($data['password']),
    //         'api_token' => Str::random(60),
    //     ]);
    // }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Category;
use App\Http\Resources\ProductResource;
use Illuminate\Http\Request;
use Session;
use Response;
use Validator;
use File;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::where('products.store_id', '=', Session::get('store')['store_id'])
            ->join('categories', 'products.category_id', '=', 'categories.id')
            ->select(
                'products.*',
                'categories.name as category'
            )
            ->paginate(5);
        return view('user/product/view_product', compact('products'));
    }

    public function apiShowAll(Request $request)
    {
        $request->validate([
            'store_id' => 'required',
        ]);

        $products = Product::where('store_id', '=', $request->get('store_id'))->get();

        return response()->json([
            'response' => 1,
            'data' => $products,
        ], 200);
    }

    public function apiShowByCategory($id)
    {
        $products = Product::where('category_id', '=', $id)->get();

        return response()->json([
            'response' => 1,
            'data' => $products,
        ], 200);
    }

    public function apiShow($id)
    {
        $product = Product::where('id', '=', $id)->get();

        return response()->json([
            'response' => 1,
            'data' => $product,
        ], 200);
    }

    public function apiAdd(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'category_id' => 'required',
            'amount' => 'required|integer',
            'price_in' => 'required|numeric',
            'price_out' => 'required|numeric',
            'measure_unit' => 'required',
            'store_id' => 'required',
        ]);

        $category = Category::find($request->get('category_id'));

        if ($category) {
            if ($category->store_id != $request->get('store_id')) {
                return response()->json([
                    'response' => 0,
                    'message' => 'Invalid category id',
                ], 401);
            }

            $photo = $request->file('image_path');
            $imageName = "";

            if ($photo) {
                $uid = auth()->user()->id;
                // $path = storage_path('images//' . $uid); //window
                $path = storage_path('images/' . $uid);  //mac
                $fileArray = array('image' => $photo);
                $rules = array('image' => 'mimes:jpeg,jpg,png,gif|required|max:10000');

                $validator = Validator::make($fileArray, $rules);

                if ($validator->fails()) {
                    return response()->json([
                        'response' => 0,
                        'error' => $validator->errors()->getMessages(),
                    ], 400);
                }

                $imageName = sha1(time()) . "." . $photo->getClientOriginalExtension();
                $photo->move($path, $imageName);
            }

            $product = new product([
                'name' => $request->get('name'),
                'category_id' => $request->get('category_id'),
                'store_id' => $request->get('store_id'),
                'amount' => $request->get('amount'),
                'price_in' => $request->get('price_in'),
                'price_out' => $request->get('price_out'),
                'measure_unit' => $request->get('measure_unit'),
                'image_path' => $imageName,
            ]);
            $product->save();

            return response()->json([
                'response' => 1,
                'message' => 'Product has been added',
                'data' => $product,
            ], 200);
        }

        return response()->json([
            'response' => 0,
            'message' => 'Invalid category id',
        ], 401);
    }

    public function apiUpdate(Request $request)
    {
        $request->validate([
            'id' => 'required',
            'name' => 'required',
            'category_id' => 'required',
            'amount' => 'required|integer',
            'price_in' => 'required|numeric',
            'price_out' => 'required|numeric',
            'measure_unit' => 'required',
            'image_path' => 'required',
            'store_id' => 'required',
        ]);

        $product = Product::find($request->get('id'));

        if ($product) {
            if ($product->store_id != $request->get('store_id')) {
                return response()->json([
                    'response' => 0,
                    'message' => 'Invalid store id',
                ], 401);
            }

            $category = Category::find($request->get('category_id'));

            if ($category) {
                if ($category->store_id != $request->get('store_id')) {
                    return response()->json([
                        'response' => 0,
                        'message' => 'Invalid category id',
                    ], 401);
                }

                $product->name = $request->get('name');
                $product->category_id = $request->get('category_id');
                $product->amount = $request->get('amount');
                $product->price_in = $request->get('price_in');
                $product->price_out = $request->get('price_out');
                $product->image_path = $request->get('image_path');
                $product->save();

                return response()->json([
                    'response' => 1,
                    'message' => 'Product has been updated',
                    'data' => $product,
                ], 200);
            }
            return response()->json([
                'response' => 0,
                'message' => 'Invalid category id',
            ], 401);
        } else {
            return response()->json([
                'response' => 0,
                'message' => 'Invalid product id',
            ], 401);
        }
    }

    public function apiDelete(Request $request)
    {
        $request->validate([
            'id' => 'required',
            'store_id' => 'required',
        ]);

        $product = Product::find($request->get('id'));

        if ($product) {
            if ($product->store_id != $request->get('store_id')) {
                return response()->json([
                    'response' => 0,
                    'message' => 'Invalid store id',
                ], 401);
            }

            $product->delete();
            return response()->json([
                'response' => 1,
                'message' => 'Product has been deleted',
            ], 200);
        }

        return response()->json([
            'response' => 0,
            'message' => 'Invalid product id',
        ], 401);
    }

    // test image
    public function apiShowImage($image)
    {
        $uid = auth()->user()->id;
        // $path = storage_path('images\\' . $uid . '\\' . $image); //window
        $path = storage_path('images/' . $uid . '/' . $image);  //mac
        // dd(    $path);

        if (file_exists($path)) {
            return response()->file($path);
        }

        return response()->json([
            'response' => 0,
            'message' => 'Image does not exist',
        ], 404);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user/product/add_product');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request      $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'category_id' => 'required',
            'amount' => 'required|integer',
            'price_out' => 'required|numeric',
            'measure_unit' => 'required',
        ]);

        $photo = $request->file('image_path');
        $imageName = "";

        if ($photo) {
            $uid = auth()->user()->id;
            // $path = storage_path('images\\' . $uid); //window
            $path = storage_path('images/' . $uid); //mac
            $fileArray = array('image' => $photo);
            $rules = array('image' => 'mimes:jpeg,jpg,png,gif|required|max:10000');

            $validator = Validator::make($fileArray, $rules);

            if ($validator->fails()) {
                return response()->json([
                    'response' => 0,
                    'error' => $validator->errors()->getMessages(),
                ], 400);
            }

            $imageName = sha1(time()) . "." . $photo->getClientOriginalExtension();
            $photo->move($path, $imageName);
        }

        $product = new product([
            'name' => $request->get('name'),
            'category_id' => $request->get('category_id'),
            'store_id' => Session::get('store')['store_id'],
            'amount' => $request->get('amount'),
            'price_in' => $request->get('price_in'),
            'price_out' => $request->get('price_out'),
            'measure_unit' => $request->get('measure_unit'),
            'image_path' => $imageName,
        ]);
        $product->save();
        return redirect('products')->with('success', 'Product has been added');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product            $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);

        return view('user/product/edit_product', compact('product'));
    }

    public function search(Request $request)
    {
        $searchData = $request->searchData;

        // start query for search

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Http\Resources\UserResource;
use Illuminate\Http\Request;
use Session;

class UserController extends Controller
{
    public function index()
    {
        $users =  User::all(); 

        return view('admin/users/view_users', compact('users'));
    }

    public function apiShow(User $user) : UserResource 
    {
        return new UserResource($user);
    }

    public function activate($id)
    {
        $users = User::find($id);
        $users->isActive = 1;
        $users->save();

        if(auth()->user()->isAdmin == 1){

            return redirect('users')->with('success', 'User has been activated');
            
        }
        return view('users');
    }

    public function deactivate($id)
    {
        
        $users = User::find($id);
        $users->isActive = 0;
        $users->save();

        return redirect('users')->with('success', 'Store has been deactivated');
    }

    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
   
        return redirect('users')->with('success', 'User has been deleted Successfully');
    }


}

resources/views/user/product/add_product.blade.php
<?php

    use App\Category;

?>
@extends('auth.layouts.layout')

@section('content')
<div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-12">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">{{ __('Add Product!') }}</h1>
                  </div>
                  <form method="POST" action="{{ route('products.store') }}" class="user" enctype="multipart/form-data">
                        @csrf

                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" name="name"
                         id="exampleFirstName" placeholder="Product Name" value="{{ old('name') }}" required autocomplete="name" autofocus>
                    </div>
                    <?php

                      $categories = Category::where('store_id','=',Session::get('store')['store_id'])->get();

                    ?>
                    
                    <div class="form-group form-row">
                        <div class="form-group ml-2 mr-4 col-md-4">
                          <label for="inputState">Category</label>
                          <select name="category_id" id="inputState" class="form-control">
                              @foreach($categories as $category)
                                  <option value="<?php echo($category->id) ?>">{{ $category->name }}</option>
                              @endforeach
                          </select>
                          <a class="small" href="{{ route('categories.create') }}">New Category ?</a>
                        </div>
                        <div class="form-group ml-4 mr-4 pt-4 col-md-4">
                            <input type="text" class="form-control form-control-user" name="amount"
                            id="exampleFirstName" placeholder="Product Amount" value="{{ old('amount') }}" autofocus>
                        </div>
                    </div>

                    <div class="form-group form-row">
                        <div class="input-group mr-4 ml-2 mb-4 col-md-4">
                          <div class="input-group-prepend">
                            <span class="input-group-text text-danger" id="validationTooltipUsernamePrepend">$</span>
                          </div>
                          <input type="text" class="form-control form-control-user" id="exampleFirstName" name="price_in"
                          placeholder="Buy in Price" aria-describedby="validationTooltipUsernamePrepend" value="{{ old('price_in') }}"
                          required autofocus>
                        </div>
                        <div class="input-group ml-4 mr-4 mb-4 col-md-4">
                          <div class="input-group-prepend">
                            <span class="input-group-text text-success" id="validationTooltipUsernamePrepend">$</span>
                          </div>
                          <input type="text" class="form-control form-control-user" id="exampleFirstName" name="price_out"
                          placeholder="Sell out Price" aria-describedby="validationTooltipUsernamePrepend" value="{{ old('price_out') }}"
                          required autofocus>
                        </div>
                    </div>

                    <div class="form-group form-row mb-4">
                      <input type="text" class="form-control form-control-user" name="measure_unit"
                       id="exampleFirstName" placeholder="Measure Unit (Can, Package, Liter...)" value="{{ old('measure_unit') }}" required autofocus>
                    </div>
                    
                    <div class="form-group form-row">
                      <div class="input-group mr-4 mb-4 pt-2 col-md-4">
                        <div class="custom-file">
                          <input type="file" accept="image/*" onchange="displayImage(this);" class="custom-file-input" id="inputGroupFile01" name="image_path">
                          <label id="inputFileText" class="custom-file-label" for="inputGroupFile01">Choose image file</label>
                        </div>
                      </div>
                      <div class="input-group mr-4 col-md-4">
                        <img src="" class="rounded" id="imageFile" alt="...">
                      </div>
                    </div>
                    <hr>

                    <button type="submit" class="btn btn-primary btn-user btn-block">
                        {{ __('Add') }}
                    </button>

                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
    
      </div>
@endsection

<script>
function displayImage(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
          $('#imageFile').attr('src', e.target.result).height("200px");
        }
        document.getElementById('inputFileText').innerHTML = input.value.replace(/.*[\/\\]/, '');
        reader.readAsDataURL(input.files[0]);
    }
}
</script>

resources/views/user/product/edit_product.blade.php
<?php

    use App\Category;

?>
@extends('auth.layouts.layout')

@section('content')
<div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-12">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">{{ __('Update Product!') }}</h1>
                  </div>
                  <form method="POST" action="{{ route('products.update', $product->id) }}" class="user">
                        @csrf
                        @method('PATCH')
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" name="name"
                         id="exampleFirstName" placeholder="Product Name" value="{{ $product->name }}" required autocomplete="name" autofocus>
                    </div>
                    <?php
                        $categories = Category::all();
                    ?>    
                    <div class="form-group form-row">
                        <div class="form-group ml-2 mr-4 col-md-4">
                          <label for="inputState">Category</label>
                          <select name="category_id" id="inputState" class="form-control">
                              @foreach($categories as $category)
                                <option value="<?php echo($category->id) ?>"
                                  @if($category->id == $product->category_id)
                                      selected
                                  @endif>
                                  {{ $category->name }}</option>
                              @endforeach
                          </select>
                          <a class="small" href="{{ route('categories.create') }}">New Category ?</a>
                        </div>
                        <div class="form-group ml-4 mr-4 pt-4 col-md-4">
                            <input type="text" class="form-control form-control-user" name="amount"
                            id="exampleFirstName" placeholder="Product Amount" value="{{ $product->amount }}" autofocus>
                        </div>
                    </div>

                    <div class="form-group form-row">
                        <div class="input-group mr-4 ml-2 mb-4 col-md-4">
                          <div class="input-group-prepend">
                            <span class="input-group-text text-danger" id="validationTooltipUsernamePrepend">$</span>
                          </div>
                          <input type="text" class="form-control form-control-user" id="exampleFirstName" name="price_in"
                          placeholder="Buy in Price" aria-describedby="validationTooltipUsernamePrepend" value="{{ $product->price_in }}"
                          required autofocus>
                        </div>
                        <div class="input-group ml-4 mr-4 mb-4 col-md-4">
                          <div class="input-group-prepend">
                            <span class="input-group-text text-success" id="validationTooltipUsernamePrepend">$</span>
                          </div>
                          <input type="text" class="form-control form-control-user" id="exampleFirstName" name="price_out"
                          placeholder="Sell out Price" aria-describedby="validationTooltipUsernamePrepend" value="{{ $product->price_out }}"
                          required autofocus>
                        </div>
                    </div>

                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" name="measure_unit"
                          id="exampleFirstName" placeholder="Measure Unit (Can, Package, Liter...)" value="{{ $product->measure_unit }}" required autofocus>
                    </div>
                    
                    <input type="hidden" class="form-control form-control-user" name="image_path"
                        id="exampleFirstName" placeholder="Product Path" value="{{ $product->image_path }}" required autofocus>
                        
                    <hr>

                    <button type="submit" class="btn btn-primary btn-user btn-block">
                        {{ __('Update') }}
                    </button>

                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
    
      </div>
<script>
  function loadImage(file) {
    var reader = new FileReader();
    reader.onload = function (e) {
      $('#imageFile').attr('src', e.target.result).height("200px");
    }
    reader.readAsDataURL(file);
  }
</script>
@endsection

resources/views/user/product/view_product.blade.php
@extends('user.layouts.layout')

@section('content')

        <!-- Begin Page Content -->
        <div class="container-fluid">
            @if(session()->get('success'))
              <div class="alert alert-success">
                {{ session()->get('success') }}  
              </div><br />
            @endif
          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800">Products</h1>
          <?php

              $product_size = $products->total();
              if(Session::get('store')['product_limit'] == "Unlimited") {
                $product_label = "Unlimited";
                $product_left = 1;
              }
              else {
                $product_left = Session::get('store')['product_limit'] - $product_size;
                $product_label = ($product_left == 0) ? "full" : $product_left." left";
              }
          ?>
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Product: {{$product_label}}</h6>
                  <div class="text-right">
                    @if(($product_left > 0) || ($product_label == "Unlimited")) 
                      <a class="btn btn-primary" href="{{ route('products.create') }}">
                        {{ __('Add Product') }}
                      </a>
                    @else 
                      <a class="btn btn-success" href="#full">
                        {{ __('Product Full') }}
                      </a>
                    @endif
                  </div>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  @if($product_size > 0)
                  <thead align="center">
                    <tr>
                      <th>No.</th>
                      <th>Name</th>
                      <th>Category</th>
                      <th>Amount</th>
                      <th>Buy in Price</th>
                      <th>Sell out Price</th>
                      <th>Image</th>
                      <th colspan="2">Action</th>
                    </tr>
                  </thead>
                  <tbody align="center">
                    <?php 
                        $count = $products->firstItem();
                    ?>
                      @foreach($products as $product)
                        <tr>
                          <td>{{ $count++ }}</td>
                          <td>{{ $product->name }}</td>
                          <td>{{ $product->category }}</td>
                          <td>{{ $product->amount }}</td>
                          <td>${{ $product->price_in }} per {{ $product->measure_unit }}</td>
                          <td>${{ $product->price_out }} per {{ $product->measure_unit }}</td>
                          <td>
                            <img src="{{url('/product/image/'.$product->image_path)}}" 
                                class="rounded" height="70px" alt="...">
                          </td>
                          <td>
                              <a class="btn btn-warning" href="{{ route('products.edit', $product->id) }}">
                                  {{ __('Update') }}
                              </a>
                          </td>
                          <td>
                              <form action="{{ route('products.destroy', $product->id) }}" method="POST">
                                  @method('DELETE')
                                  @csrf
                                  <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')">
                                      {{ __('Delete') }}
                                  </button>
                              </form>
                          </td>
                        </tr>
                      @endforeach
                      @while(($count-1) % 5 != 0)
                      <tr>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                      </tr>
                      <?php $count++ ?>
                      @endwhile
                  </tbody>
                  @else
                      <p>You have 0 product!</p>
                  @endif
                </table>
                  <div class="text-right">
                      {{ $products->onEachSide(5)->links() }}
                  </div>
              </div>
            </div>
          </div>

        </div>
        <!-- /.container-fluid -->
@endsection