routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('generate-pdf','TransactionInfoController@generatePDF');

Route::get('/', function () {
    return view('guest/home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// new
// Route::post('/register', 'AuthController@register');
// Route::post('/login', 'AuthController@login');

Route::get('/admin', function () {
    if (Auth::check()) {
        return redirect()->action('HomeController@index');
    }
    return view('auth.admin.login');
});

Route::get('/guest', function () {
    return view('guest/home');
});
Route::get('/user/chooseStore', 'StoreController@chooseStore')->name('chooseStore');

Route::get('/plan_price/json', 'PlanPriceController@listPrice');

// Route::get('/guest/store', function () {
//     return view('guest/store/choose_store');
// });
// Route::get('/guest/store/create', function () {
//     return view('guest/store/create_store');
// });

// user middleware
Route::middleware('auth')->group(function () {
    Route::get('/user', function () {
        
    });
    Route::get('/user/inventory', function () {
        return view('user/inventory');
    });
    Route::get('/user/report', function () {
        return view('user/report');
    });
    Route::resource('stores', 'StoreController');
    Route::get('stores/{id}/activate', 'StoreController@activate');
    Route::resource('categories', 'CategoryController');
    Route::resource('products', 'ProductController');
    Route::get('product/image/{image}', 'ProductController@apiShowImage');
    
    Route::resource('contacts', 'ContactController');
    Route::resource('transactions', 'TransactionController');
    Route::resource('transaction_infos', 'TransactionInfoController');
    // Route::get('search','ProductController@search');
    
    // admin middleware
    Route::middleware('admin')->group(function () {
        Route::get('/admin/home', function () {
            return view('admin.dashboard');
        });
        Route::resource('plan_prices', 'PlanPriceController');
        Route::get('stores/{id}/deactivate', 'StoreController@deactivate');

        Route::resource('users', 'UserController');
        Route::get('users/{id}/activate', 'UserController@activate');
        Route::get('users/{id}/deactivate', 'UserController@deactivate');
    });
});

app/User.php
<?php

namespace App;

use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 
    ];

    // protected function create(array $data)
    // {
    //     return User::create([
    //         'name' => $data['name'],
    //         'email' => $data['email'],
    //         'password' => Hash::make($data['password']),
    //         'api_token' => Str::random(60),
    //     ]);
    // }

}

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Transaction;
use App\Transaction_info;
use App\Product;
use App\Contact;

use App\Http\Resources\TransactionResource;
use App\Http\Resources\TransactionInfoResource;
use Illuminate\Http\Request;
use Session;
use Illuminate\Support\Facades\Log;


class TransactionController extends Controller
{
/**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $transactions = Transaction::where('transactions.store_id','=',Session::get('store')['store_id'])
                            ->leftjoin('contacts', 'transactions.contact_id', '=', 'contacts.id')
                            ->select('transactions.*',
                            'contacts.name as contact')
                            ->paginate(5);

        return view('user/transaction/view_transaction', compact('transactions'));
    }

    public function apiShowAll(Request $request)
    {
        $request->validate([
            'store_id'=>'required',
        ]);

        $transactions = Transaction::where('store_id','=',$request->get('store_id'))
                            ->get()->toArray();

        if ($transactions) {
            for ($i=0; $i<sizeof($transactions); $i++) {
                $contact = Contact::find($transactions[$i]['contact_id']);
                
                $transaction_infos = Transaction_info::where('transaction_id', '=', $transactions[$i]['id'])
                                ->leftjoin('products', 'transaction_infos.product_id', '=', 'products.id')
                                ->select('products.*', 'transaction_infos.*')
                                ->get();

                $transactions[$i]['contact_id'] = $contact;
                $transactions[$i]['transaction_info'] = $transaction_infos;
            }
        }

        return response()->json([
            'response' => 1,
            'data' => $transactions,
        ], 200);
    }

    public function apiShow($id)
    {
        $transaction = Transaction::where('id','=',$id)->get();
        $contact = Contact::find($transaction['contact_id']);

        $transaction_infos = Transaction_info::where('transaction_id', '=', $id)
                            ->join('products', 'transaction_infos.product_id', '=', 'products.id')
                            ->select('products.*', 'transaction_infos.*')
                            ->get();
                            
        $transaction['contact_id'] = $contact;
        $transaction['transaction_info'] = $transaction_infos;
        
        return response()->json([
            'response' => 1,
            'data' => $transaction,
        ], 200);
    }

    function apiShowByType($store_id, $is_sell)
    {
        $transactions = Transaction::where('store_id','=',$store_id)
                            ->where('isSell', '=', $is_sell)
                            ->get()->toArray();
        if ($transactions) {
            for ($i=0; $i<sizeof($transactions); $i++) {
                $contact = Contact::find($transactions[$i]['contact_id']);
                
                $transaction_infos = Transaction_info::where('transaction_id', '=', $transactions[$i]['id'])
                                ->join('products', 'transaction_infos.product_id', '=', 'products.id')
                                ->select('products.*', 'transaction_infos.*')
                                ->get();

                $transactions[$i]['contact_id'] = $contact;
                $transactions[$i]['transaction_info'] = $transaction_infos;
            }
        }

        return response()->json([
            'response' => 1,
            'data' => $transactions,
        ], 200);
    }

    public function apiShowSaleList(Request $request)
    {
        $request->validate([
            'store_id'=>'required',
        ]);

        return $this->apiShowByType($request->get('store_id'), true);
    }

    public function apiShowPurchaseList(Request $request)
    {
        $request->validate([
            'store_id'=>'required',
        ]);

        return $this->apiShowByType($request->get('store_id'), false);
    }

    public function apiAdd(Request $request) 
    {
        $request->validate([
            'product_id' => 'required',
            'product_amount' => 'required',
            'store_id' => 'required',
            'total_price' => 'required',
        ]);

        $is_sell = $request->get('options') == "sell_out";
        $total_price = $request->get('total_price');
        $contact_id = $request->get('contact_id');
        $store_id = $request->get('store_id');

        $product_id = $request->get('product_id');
        $product_amount = $request->get('product_amount');
        $product = Product::find($product_id);

        if ($product) {
            if ($product->store_id == $store_id) {
                if ($contact_id != null) {
                    $contact = Contact::find($contact_id);
                    if (!$contact) {
                        return response()->json([
                            'response' => 0,
                            'message' => 'Invalid contact id',
                        ], 401);
                    }
                }

                if ($is_sell) {
                    if ($product->amount < $product_amount) {
                        return response()->json([
                            'response' => 0,
                            'message' => 'Invalid product amoung',
                        ], 401);
                    }
                    $product->amount = $product->amount - $product_amount;
                }
                else {
                    $product->amount = $product->amount + $product_amount;
                }
                $product->save();

                $transaction = new Transaction([
                    'isSell' => $is_sell,
                    'total_price' => $total_price,
                    'contact_id' => $contact_id,
                    'store_id' => $store_id,
                ]);
                $transaction->save();
                $transaction_id = $transaction->id;
                
                $transaction_info = new Transaction_info([
                    'amount' => $product_amount,
                    'product_id' => $product_id,
                    'transaction_id' => $transaction_id,
                    'store_id' => $store_id,
                ]);
                $transaction_info->save();

                return response()->json([
                    'response' => 1,
                    'message' => 'Transaction has been added',
                    'data' => $transaction,
                    'info' => $transaction_info,
                ], 200);
            }
        }

        return response()->json([
            'response' => 0,
            'message' => 'Invalid product id',
        ], 401);
    }

    public function apiDelete(Request $request)
    {
        $request->validate([
            'id' => 'required',
            'store_id' => 'required',
        ]);
        
        $transaction = Transaction::find($request->get('id'));

        if ($transaction) {
            if ($transaction->store_id != $request->get('store_id')) {
                return response()->json([
                    'response' => 0,
                    'message' => 'Invalid store id',
                ], 401);
            }

            Transaction_info::where('transaction_id', '=', $request->get('id'))->delete();
            $transaction->delete();

            return response()->json([
                'response' => 1,
                'message' => 'Transaction has been deleted',
            ], 200);
        }

        return response()->json([
            'response' => 0,
            'message' => 'Invalid transaction id',
        ], 401);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user/transaction/add_transaction');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'product_name'=>'required',
            'product_amount'=>'required',
        ]);

        $is_sell = $request->get('options') == "sell_out";
        $store_id = Session::get('store')['store_id'];
        $contact_id = $request->get('contact_id');
        $total_price = $request->get('total_price');

        $product_name = $request->get('product_name');
        $product_amount = $request->get('product_amount');

        if (count($product_name) !== count(array_unique($product_name))) {
            return redirect()->back()->withErrors(['product can not be duplicate'])->withInput();
        }

        // store transaction
        // need: isSell(bool); total_price(int); contact_id(int); store_id(int)
        $transaction = new Transaction([
            'isSell' => $is_sell,
            'total_price' => $total_price,
            'contact_id' => $contact_id,
            'store_id' => $store_id,
        ]);
        $transaction->save();
        $transaction_id = $transaction->id;

        // loop and store transaction_info
        // need: amount(int); product_id(int); transaction_id(int); store_id(int)
        for ($i=0; $i<sizeof($product_name); $i++) {
            $product = json_decode($product_name[$i]);
            $pId = $product->id;
            $pAmount = $product_amount[$i];

            if ($is_sell) { // if buy in
                $product = Product::find($pId);
                $product->amount = $product->amount - $pAmount;
                $product->save();
            }
            else { // if buy in
                $product = Product::find($pId);
                $product->amount = $product->amount + $pAmount;

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Http\Resources\UserResource;
use Illuminate\Http\Request;
use Session;

class UserController extends Controller
{
    public function index()
    {
        $users =  User::all(); 

        return view('admin/users/view_users', compact('users'));
    }

    public function apiShow(User $user) : UserResource 
    {
        return new UserResource($user);
    }

    public function activate($id)
    {
        $users = User::find($id);
        $users->isActive = 1;
        $users->save();

        if(auth()->user()->isAdmin == 1){

            return redirect('users')->with('success', 'User has been activated');
            
        }
        return view('users');
    }

    public function deactivate($id)
    {
        
        $users = User::find($id);
        $users->isActive = 0;
        $users->save();

        return redirect('users')->with('success', 'Store has been deactivated');
    }

    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
   
        return redirect('users')->with('success', 'User has been deleted Successfully');
    }


}

resources/views/user/transaction/view_info_transaction.blade.php
@extends('auth.layouts.layout')

@section('content')

<div class="container">
        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-12">
                <div class="p-5">
                    <div class="text-center">
                      <h1 class="h2 text-gray-700 mb-2">{{ __('Invoice') }}</h1>
                      <h1 class="h5 text-gray-700 mb-2">{{ __('#'.$transaction["id"]) }}</h1>
                    </div>
                    <div class="form-group col-md-4">
                        <label class="h5 text-gray-800 mr-2">Type:</label>
                        <label class="text-gray-800">{{$transaction["isSell"] ? "Sell out" : "Buy in"}}</label>
                    </div>

                    <div class="form-group col-md-4">
                        <div class="row-md-4">
                            <label class="h5 text-gray-800 mr-2">{{$transaction["isSell"] ? "Billed from:" : "Billed To:" }}</label>
                            <label>{{$transaction["contact_name"] ? $transaction["contact_name"] : "(No Name)"}}</label>
                        </div>
                        <div>
                            <label>Role: {{$transaction["contact_role"] ? $transaction["contact_role"] : "(No Role)"}}</label>
                        </div>
                        <div>
                            <label>Phone: {{$transaction["contact_phone"] ? $transaction["contact_phone"] : "(No Phone)"}}</label>
                        </div>
                    </div>

                    <div class="form-group col-md-4">
                      <?php
                        $format = 'Y-m-d H:i:s';
                        $date = DateTime::createFromFormat($format, $transaction["created_at"]);
                      ?>
                        <label class="h5 text-gray-800 mr-2">Created Date:</label>
                        <label class="text-gray-800">{{$date->format('D-d-M-Y')}}</label>
                    </div>

                    <table class="table" style="table-layout: fixed;">
                        <thead align="center">
                          <tr class="heading-invoice">
                            <th scope="col">Product</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Totals</th>
                          </tr>
                        </thead>
                        <tbody id="tbody_product" align="center">
                          @foreach ($transaction_infos as $item)
                            <tr>
                              <td>{{$item["product_name"]}}</td>
                              <td>${{$item["product_price"]}}</td>
                              <td>{{$item["product_amount"]}}</td>
                              <td scope="col">${{$item["product_price"] * $item["product_amount"]}}</td>
                            </tr>
                          @endforeach
                        </tbody>
                        <tfoot>
                          <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th scope="col">Total Price: ${{$transaction["total_price"]}}</th>
                          </tr>
                        </tfoot>
                    </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
@endsection

resources/views/user/transaction/view_transaction.blade.php
@extends('user.layouts.layout')

@section('content')

        <!-- Begin Page Content -->
        <div class="container-fluid">
            @if(session()->get('success'))
              <div class="alert alert-success">
                {{ session()->get('success') }}  
              </div><br />
            @endif
          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800">Transactions</h1>
          <?php
              $transaction_size = $transactions->total();
          ?>
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Total Transactions: {{$transaction_size}}</h6>
                  <div class="text-right">
                      <a class="btn btn-primary" href="{{ route('transactions.create') }}">
                        {{ __('Add Transaction') }}
                      </a>
                  </div>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  @if($transaction_size > 0)
                  <thead align="center">
                    <tr>
                      <th>No.</th>
                      <th>Type</th>
                      <th>To</th>
                      <th>Total Price</th>
                      <th>Date</th>
                      <th colspan="2">Action</th>
                    </tr>
                  </thead>
                  <tbody align="center">
                    <?php 
                        $count = $transactions->firstItem();
                    ?>
                      @foreach($transactions as $transaction)
                        <tr>
                          <td>{{ $count++ }}</td>
                          <td>{{ $transaction->isSell ? "Sell out" : "Buy in" }}</td>
                          <td>{{ $transaction->contact ? $transaction->contact : "(No Name)" }}</td>
                          <td>${{ $transaction->total_price }}</td>
                          <td>{{ $transaction->created_at->format('D-d-M-Y') }}</td>
                          <td>
                              <a class="btn btn-success" href="{{ route('transactions.show', $transaction->id) }}">
                                  {{ __('View') }}
                              </a>
                          </td>
                          <td>
                              <form action="{{ route('transactions.destroy', $transaction->id) }}" method="POST">
                                  @method('DELETE')
                                  @csrf
                                  <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')">
                                      {{ __('Delete') }}
                                  </button>
                              </form>
                          </td>
                        </tr>
                      @endforeach
                      @while(($count-1) % 5 != 0)
                      <tr>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                      </tr>
                      <?php $count++ ?>
                      @endwhile
                  </tbody>
                  @else
                      <p>You have 0 Transaction!</p>
                  @endif
                </table>
                  <div class="text-right">
                      {{ $transactions->onEachSide(5)->links() }}
                  </div>
              </div>
            </div>
          </div>

        </div>
        <!-- /.container-fluid -->
@endsection